// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OutfitRandomizer.Api.Data;

#nullable disable

namespace OutfitRandomizer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220010843_SeedInitialClothes")]
    partial class SeedInitialClothes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OutfitRandomizer.Api.Models.ClothingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Spodnie Zwykłe",
                            Name = "sOliver niskie jeans"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Spodnie Zwykłe",
                            Name = "szare jeans"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Spodnie Zwykłe",
                            Name = "czarne jeans"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Spodnie Zwykłe",
                            Name = "kratka"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Sukienki",
                            Name = "polar ruda"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Sukienki",
                            Name = "prosta czarna"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Sukienki",
                            Name = "kwiaty ruda"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Sukienki",
                            Name = "paski czarno-biała"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "my little pony"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "długa czarna"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "kuromi czarna"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Bluzy",
                            Name = "krótka zielona"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Bluzy",
                            Name = "hollister żółta"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Bluzy",
                            Name = "sweterek miękki biała"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
