// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OutfitRandomizer.Api.Data;

#nullable disable

namespace OutfitRandomizer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220011028_FullClothingSeed")]
    partial class FullClothingSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OutfitRandomizer.Api.Models.ClothingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Spodnie Zwykłe",
                            Name = "sOliver niskie jeans"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Spodnie Zwykłe",
                            Name = "szare jeans"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Spodnie Zwykłe",
                            Name = "czarne jeans"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Spodnie Zwykłe",
                            Name = "szare jeans niskie luźne"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Spodnie Zwykłe",
                            Name = "kratka"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Spodnie Zwykłe",
                            Name = "Ciasne jeans niebieskie"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Spodnie Zwykłe",
                            Name = "niebieskie jeans"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Spodnie Zwykłe",
                            Name = "bigstar niskie"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Legginsy",
                            Name = "śliskie"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Legginsy",
                            Name = "górskie"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Legginsy",
                            Name = "ciasne"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Spodnie Dresowe",
                            Name = "beżowe"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Spodnie Dresowe",
                            Name = "różowe"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Spodnie Dresowe",
                            Name = "czarne"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Spodnie Dresowe",
                            Name = "brązowe"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Spódnice",
                            Name = "plisowana czarna"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Spódnice",
                            Name = "gotycka czarna"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Spódnice",
                            Name = "prosta różowa"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Sukienki",
                            Name = "polar ruda"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Sukienki",
                            Name = "prosta czarna"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Sukienki",
                            Name = "kwiaty ruda"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Sukienki",
                            Name = "paski czarno-biała"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Sukienki",
                            Name = "długa niebieska"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Sukienki",
                            Name = "mini obcisła czarna"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Sukienki",
                            Name = "kwiatowa ramiączka kolorowa"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Sukienki",
                            Name = "sztruks czarna"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Sukienki",
                            Name = "sztruks ruda"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Sukienki",
                            Name = "kropki zielona"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Sukienki",
                            Name = "paski stara letnia czarno-biała"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Sukienki",
                            Name = "kropki czarna"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Sukienki",
                            Name = "pastelowa kolorowa"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Sukienki",
                            Name = "japońska pomarańczowa"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Sukienki",
                            Name = "obcisła złote ramiączka ruda"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Sukienki",
                            Name = "uczennica krata"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Sukienki",
                            Name = "miękka długi rękaw ruda"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "my little pony"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "długa czarna"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "biała twarz czarna"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "ramiączka czarna"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "jedwab wiśniowa"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "jedwab różowa"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "paski niebieska"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "kuromi czarna"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "napis słońce biała"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "jedwab ramiączka prosta czarna"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "różowa twarz czarna"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "jedwab falbanki czarna"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "ramiączka stara czarna"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "fioletowa twarz biała"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "barbie biała"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "gra dziewczynka czarna"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "ramiączka szara"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "koszula kwiaty zielona"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "koszula pomarańczowa"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "szkielety dziewczynka czarna"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "zioło dziewczynka czarna"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "ramiączka sztruks szara"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "hollister biała"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Bluzki (Luźniejsze)",
                            Name = "liście biała"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Bluzki (Obcisłe)",
                            Name = "kuromi fioletowa"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Bluzki (Obcisłe)",
                            Name = "Bambi różowa"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Bluzki (Obcisłe)",
                            Name = "miś różowa"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Bluzki (Obcisłe)",
                            Name = "cienka beżowa"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Bluzki (Obcisłe)",
                            Name = "długa czarna"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Bluzki (Obcisłe)",
                            Name = "kratka czarno-biała"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Bluzki (Obcisłe)",
                            Name = "króliczek różowa"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Bluzki (Obcisłe)",
                            Name = "diamenciki czarna"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Bluzki (Obcisłe)",
                            Name = "winx różowa"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Bluzki (Obcisłe)",
                            Name = "dziurawa beżowa"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Bluzki (Obcisłe)",
                            Name = "paski pomarańczowo-szara"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Bluzki (Obcisłe)",
                            Name = "sztruks czarna"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Bluzki (Obcisłe)",
                            Name = "długa niebieska"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Bluzy",
                            Name = "krótka zielona"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Bluzy",
                            Name = "krótka czarna"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Bluzy",
                            Name = "prosta czarna"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Bluzy",
                            Name = "hollister żółta"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Bluzy",
                            Name = "barbie biała"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Bluzy",
                            Name = "prosta pomarańczowa"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Bluzy",
                            Name = "golf biały"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Bluzy",
                            Name = "sportowa szara"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Bluzy",
                            Name = "róże czarna"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Bluzy",
                            Name = "napisy brązowa"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Bluzy",
                            Name = "prosta szara"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Bluzy",
                            Name = "kws szara"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Bluzy",
                            Name = "góry zielona"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Bluzy",
                            Name = "komplet beżowa"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Bluzy",
                            Name = "sweterek miękki biała"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
